"""initial schema

Revision ID: 8aab4549d07b
Revises: 
Create Date: 2026-06-04 23:52:24.975017
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.database  # noqa: F401  (GUID type used in column definitions)


# revision identifiers, used by Alembic.
revision: str = '8aab4549d07b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', app.database.GUID(), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('is_header', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_concepts_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_section'), ['section'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('clabe', sa.String(length=18), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='supplierstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_legal_name'), ['legal_name'], unique=False)

    op.create_table('users',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'engineer', 'accountant', 'field_admin', 'supervisor', 'cfo', 'treasurer', 'ceo', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.database.GUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', app.database.GUID(), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('solicitudes',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('request_type', sa.Enum('contractor_estimate', 'supplier_invoice', 'reimbursement', 'government_fee', 'utility', 'service', 'tax', 'other', name='requesttype', native_enum=False), nullable=False),
    sa.Column('supplier_id', app.database.GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('proposed_concept_id', app.database.GUID(), nullable=True),
    sa.Column('final_concept_id', app.database.GUID(), nullable=True),
    sa.Column('proposed_payment_week', sa.String(length=10), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'correction_requested', 'supervisor_approved', 'cfo_approved', 'deferred', 'rejected', 'cancelled', name='solicitudstatus', native_enum=False), nullable=False),
    sa.Column('captured_by', app.database.GUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('supervisor_reviewed_by', app.database.GUID(), nullable=True),
    sa.Column('supervisor_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('cfo_reviewed_by', app.database.GUID(), nullable=True),
    sa.Column('cfo_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cfo_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['final_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['proposed_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['supervisor_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_captured_by'), ['captured_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_folio'), ['folio'], unique=True)
        batch_op.create_index(batch_op.f('ix_solicitudes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_clearances',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('supplier_id', app.database.GUID(), nullable=False),
    sa.Column('status', sa.Enum('cleared', 'pending', 'blocked', name='clearancestatus', native_enum=False), nullable=False),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('compliance_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', app.database.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_clearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_clearances_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('solicitud_id', app.database.GUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path_or_s3_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('uploaded_by', app.database.GUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_solicitud_id'), ['solicitud_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('solicitud_id', app.database.GUID(), nullable=False),
    sa.Column('author_id', app.database.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_solicitud_id'), ['solicitud_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_solicitud_id'))

    op.drop_table('comments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_solicitud_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('supplier_clearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_clearances_supplier_id'))

    op.drop_table('supplier_clearances')
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_status'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_folio'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_captured_by'))

    op.drop_table('solicitudes')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_legal_name'))

    op.drop_table('suppliers')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_section'))
        batch_op.drop_index(batch_op.f('ix_concepts_parent_id'))
        batch_op.drop_index(batch_op.f('ix_concepts_code'))

    op.drop_table('concepts')
    # ### end Alembic commands ###
